### <font color='purple'><b>Importing the libraries :

In [14]:
import glob     # to extract the paths under directory and sub-directories
import textract      # to read .docx files
from pdfminer.high_level import extract_text    # to read .pdf files
from win32com import client as wc     # to read .doc files
import pandas as pd

### <font color='purple'><b>Data Extraction :

#### <font color='magenta'><b><I>paths of .doc files :

In [4]:
files3 = glob.glob('C:\\Users\\Dell\\Downloads\\Resumes-20230307T022209Z-001\\resume\\**\\*.doc',recursive=True)
for i in files3:
    print(i)

C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\React Developer_PavasGoswami.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\React Developer_Vinay Reddy.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\React JS Developer_AnjaniPriyadarshini.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_G Ananda Rayudu.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_Gangareddy.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_Priyanka Ramadoss.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_srinivasarao.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_Vinod Akkala.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\PeopleSoft DBA_Ganesh Alladi.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Finance_Arun Venu.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Finance_Pritam Biswas.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Finance_Rahul Ahuja.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft FSCM_R Ahmed.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\SQL Developer Lightning insight\Nazeer Basha.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\SQL Developer Lightning insight\Priyanka L.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\SQL Developer Lightning insight\Tatikonda Kiran Kumar.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Hari Krishna M_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Harikrishna Akula_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Hima Mendu_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\J. Sumanth Royal_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Madeeswar A_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Naresh Babu Cherukuri_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Punugoti Swetha_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\ShireeshKumar_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Sri Krishna S_Hexaware.doc
C:\Users\Dell\Downloads\Resumes-20230307T022209Z-001\resume\Resumes\workday resumes\Venkateswarlu B_Hexaware.doc

#### <font color='magenta'><b><I>paths of .docx files :

In [40]:
filesx = glob.glob('C:\\Users\Dell\\Downloads\\Resumes-20230307T054753Z-001\\resume\\**\\*.docx',recursive=True)
for i in filesx:
    print(i)

C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Internship_Ravali_Musquare Technologies (1).docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Internship_Susovan Bag_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Deepakreddy.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Haripriya.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Kamalakar Reddy.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Naveen sadhu.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Pragnya.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Sarala Madasu-converted.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Developer_Thirupathiamma.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Dev_Krishna Kanth.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React Dev_Krishna Kanth_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React JS Developer_KotaniDurgaprasad[3_1] (1)-converted.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\React JS Developer_Venkatalakshmi (1)-converted.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_kambala sai surendra_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_M Lokesh Babu_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_M Lokesh.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_MD Khizaruddin Rauf _Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_Pranish Sonone_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_Ranga Gaganam_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_Shaik Abdul Sharuk_Musquare Technologies.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_AnubhavSingh.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_Murali.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_SirazuddinMohammad.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft Admin_Varkala Vikas.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\PeopleSoft DBA_Vivekanand Sayana.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft FSCM_HariNarayana.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft FSCM_Murali.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft FSCM_PriyabrataHota.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Peoplesoft FSCM_SUJATHA.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Peoplesoft resumes\Resume_Subha Santosh_Peoplesoft FSCM.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Anil kumar.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\AradhanaTripathi[4_0].docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Buddha Vamsi.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\kamballapradeep.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Neeraj Mishra.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\premsai.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\PSyamKumar[2_3].docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Rajupavanakumari[2_10].docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Ramalakshmi K.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\RameshNataru[3_4].docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\SQL Developer Lightning insight\Vinod B.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\ChinnaSubbarayuduM_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\Gopi Krishna_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\Himaja G_(Hexaware).docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\Jyotiverma_Heaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\MooraboyinaGuravaiah_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\P V Sai Krishna_ Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\RahulM_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\RameshP_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\Srikanth-Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\SSKumar_Hexaware.docx
C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\workday resumes\Vinay Kumar_Hexaware.docx

#### <font color='magenta'><b><I>paths of .pdf files :

In [41]:
files2 = glob.glob('C:\\Users\Dell\\Downloads\\Resumes-20230307T054753Z-001\\resume\\**\\*.pdf',recursive=True)
for i in files2:
    print(i)

C:\Users\Dell\Downloads\Resumes-20230307T054753Z-001\resume\Resumes\Reactjs Developer_Prabakaran_Musquare Technologies.pdf

#### <font color='magenta'><b><I>total number of files :

In [44]:
tot = files3 + filesx + files2
print('Total no. of extracted files =', len(tot))

Total no. of extracted files = 79

#### <font color='green'><b>Text Extraction of .doc files and converting it to pandas dataframe along with the filenames as categories :

In [26]:
files3 = glob.glob('C:\\Users\Dell\\Downloads\\Resumes-20230307T054753Z-001\\resume\\**\\*.doc',recursive=True)
res_list = []
for i in files3:
    w = wc.Dispatch('Word.Application')
    doc = w.Documents.Open(i)
    #text = line.replace('\t', ' ') for line in doc.content().split('\r') if line
    res_list.append(doc.content())
    #print(res_list)

df3 = pd.DataFrame(res_list,columns=['resume_text'])
df3 = df3.join(df1)
df3

,resume_text,category
0,\r\r PROFILE\rSearching for the opportunity ...,React Developer_PavasGoswami.doc
1,Maryala Vinay Reddy\r\rProfessional Summary:\t...,React Developer_Vinay Reddy.doc
2,CURRICULUM VITAE\r\r\r\rAnjani Priyadarshini\r...,React JS Developer_AnjaniPriyadarshini.doc
3,\r\r\r\r\r\r\t\r\rProfile Summary:\t\t\t\t\t\t...,Peoplesoft resumes
4,PeopleSoft Database Administrator\r ...,Peoplesoft resumes
5,"Priyanka Ramadoss\r61/46, MountPleasant, \rCoo...",Peoplesoft resumes
6,PEOPLESOFT ADMINISTRATOR\r\r\rSRINIVAS.K \t\t\...,Peoplesoft resumes
7,Vinod Akkala ...,Peoplesoft resumes
8,PeopleSoft Admin/PeopleSoft DBA\r\rGanesh All...,Peoplesoft resumes
9,Arun Venu\r\r EXPERIENCE SUMMARY\t\r\rExperie...,Peoplesoft resumes
10,Personal Details\t\t\r\rName\rPritam Biswas...,Peoplesoft resumes
11,Rahul Ahuja\r---------------------------------...,Peoplesoft resumes
12,\rR Ahmed ...,Peoplesoft resumes
13,\r\r Hyderabad\rNazeer Basha\rSQL and Power...,SQL Developer Lightning insight
14,SQL SER...,SQL Developer Lightning insight
15,Career objective\r\t\rA rewarding opportunity ...,SQL Developer Lightning insight
16,Hari Krishna M\r\r\rSummary:\rA result oriente...,workday resumes
17,Harikrishna Akula ...,workday resumes
18,HIMA.MENDU\r \r\rCareer Objective\rTo continu...,workday resumes
19,\t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\r\t\rP...,workday resumes
20,\t\t\t\t\tMadeeswar A\r\t\r\t\rPROFILE SUMMARY...,workday resumes
21,Name\t: Naresh Babu Cherukuri\r\rObjective:\rT...,workday resumes
22,\r\r\r3.3 years of IT experience as Workda...,workday resumes
23,Shireesh Balasani ...,workday resumes
24,\tWorkday Integration Consultant\r\rName ...,workday resumes
25,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...,workday resumes

In [27]:
df3.loc[0:2,'category'] = 'ReactJS Developer'
df3.loc[3:12,'category'] = 'Peoplesoft'
df3.loc[13:15,'category'] = 'SQL Developer'
df3.loc[16:25,'category'] = 'Workday'
df3

                                          resume_text           category
0   \r\r
PROFILE\rSearching for the opportunity ...  ReactJS Developer
1   Maryala Vinay Reddy\r\rProfessional Summary:\t...  ReactJS Developer
2   CURRICULUM VITAE\r\r\r\rAnjani Priyadarshini\r...  ReactJS Developer
3   \r\r\r\r\r\r\t\r\rProfile Summary:\t\t\t\t\t\t...         Peoplesoft
4   PeopleSoft Database Administrator\r           ...         Peoplesoft
5   Priyanka Ramadoss\r61/46, MountPleasant, \rCoo...         Peoplesoft
6   PEOPLESOFT ADMINISTRATOR\r\r\rSRINIVAS.K \t\t\...         Peoplesoft
7   Vinod Akkala                                  ...         Peoplesoft
8    PeopleSoft Admin/PeopleSoft DBA\r\rGanesh All...         Peoplesoft
9   Arun Venu\r\r  EXPERIENCE SUMMARY\t\r\rExperie...         Peoplesoft
10  Personal Details\t\t\r\rName\rPritam Biswas...         Peoplesoft
11  Rahul Ahuja\r---------------------------------...         Peoplesoft
12  \rR Ahmed                                     ...         Peoplesoft
13
\r\r Hyderabad\rNazeer Basha\rSQL and Power...      SQL Developer
14                                         SQL SER...      SQL Developer
15  Career objective\r\t\rA rewarding opportunity ...      SQL Developer
16  Hari Krishna M\r\r\rSummary:\rA result oriente...            Workday
17  Harikrishna Akula                             ...            Workday
18  HIMA.MENDU\r  \r\rCareer Objective\rTo continu...            Workday
19  \t\t\t\t\t\t\tName:\tJ. Sumanth Royal.\r\t\rP...            Workday
20  \t\t\t\t\tMadeeswar A\r\t\r\t\rPROFILE SUMMARY...            Workday
21  Name\t: Naresh Babu Cherukuri\r\rObjective:\rT...            Workday
22  \r\r\r3.3 years of IT experience as Workda...            Workday
23  Shireesh Balasani                             ...            Workday
24  \tWorkday Integration Consultant\r\rName      ...            Workday
25  Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...            Workday

#### <font color='green'><b>Text Extraction of .docx files and converting it to pandas dataframe along with the filenames as categories :

In [32]:
files1 = glob.glob('C:\\Users\Dell\\Downloads\\Resumes-20230307T054753Z-001\\resume\\**\\*.docx',recursive=True)
res_list1 = []
dfx = pd.DataFrame(files1,columns=['category'])
dfx = dfx['category'].str.split('\\').str[7]
dfx.columns = ['category']

for i in files1:
    a = textract.process(i)
    res_list1.append((a).decode('utf-8'))

dfr = pd.DataFrame(res_list1,columns=['resume_text'])

dfr = dfr.join(dfx)
dfr

,resume_text,category
0,Name: Ravali P \n\n\n\n ...,Internship_Ravali_Musquare Technologies (1).docx
1,SUSOVAN BAG \n\nSeeking a challenging po...,Internship_Susovan Bag_Musquare Technologies.docx
2,Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...,React Developer_Deepakreddy.docx
3,HARIPRIYA BATTINA \n\nExperience as UI Develop...,React Developer_Haripriya.docx
4,KAMALAKAR REDDY. A \n\nLinked In: https://www....,React Developer_Kamalakar Reddy.docx
5,Naveen Sadhu\n\n\n\n\n\nTitle: software develo...,React Developer_Naveen sadhu.docx
6,PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...,React Developer_Pragnya.docx
7,"SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...",React Developer_Sarala Madasu-converted.docx
8,Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...,React Developer_Thirupathiamma.docx
9,Ui-Developer/ React JS Developer \n\nNAME: KRI...,React Dev_Krishna Kanth.docx
10,Ui-Developer/ React JS Developer \n\nNAME: KRI...,React Dev_Krishna Kanth_Musquare Technologies....
11,Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...,React JS Developer_KotaniDurgaprasad[3_1] (1)-...
12,Venkatalakshmi Pedireddy\n\nSoftware Developer...,React JS Developer_Venkatalakshmi (1)-converte...
13,KAMBALA SAI SURENDRA \n\n \n\n \n\n \n\n\n\n...,Reactjs Developer_kambala sai surendra_Musquar...
14,MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...,Reactjs Developer_M Lokesh Babu_Musquare Techn...
15,MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...,Reactjs Developer_M Lokesh.docx
16,MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n ...,Reactjs Developer_MD Khizaruddin Rauf _Musquar...
17,Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...,Reactjs Developer_Pranish Sonone_Musquare Tech...
18,Ranga Gaganam \n\n\n\n \n\nProfessional\n\n \...,Reactjs Developer_Ranga Gaganam_Musquare Techn...
19,SHAIK ABDUL SHARUK \n\n2 years’ Experience i...,Reactjs Developer_Shaik Abdul Sharuk_Musquare ...
20,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,Peoplesoft resumes
21,Classification: Internal\n\nClassification: In...,Peoplesoft resumes
22,"SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...",Peoplesoft resumes
23,PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...,Peoplesoft resumes
24,PeopleSoft Administration\n\n \n\nVivekanand S...,Peoplesoft resumes
25,Hari Narayana \t\t \n\n\t\n\n\n\n...,Peoplesoft resumes
26,Murali\t\t \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...,Peoplesoft resumes
27,Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...,Peoplesoft resumes
28,Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...,Peoplesoft resumes
29,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,Peoplesoft resumes
30,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,SQL Developer Lightning insight
31,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,SQL Developer Lightning insight
32,BUDDHA VAMSI ...,SQL Developer Lightning insight
33,KAMBALLA PRADEEP ...,SQL Developer Lightning insight
34,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...,SQL Developer Lightning insight
35,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...,SQL Developer Lightning insight
36,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...,SQL Developer Lightning insight
37,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...,SQL Developer Lightning insight
38,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,SQL Developer Lightning insight
39,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...,SQL Developer Lightning insight
40,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,SQL Developer Lightning insight
41,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,workday resumes
42,Name : Gopi Krishna Reddy\n\n\t\t\t\t ...,workday resumes
43,G Himaja\n\n ...,workday resumes
44,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...,workday resumes
45,Mooraboyina Guravaiah\n\nWorkday Integration S...,workday resumes
46,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...,workday resumes
47,Workday HCM Techno functional Consultant ...,workday resumes
48,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...,workday resumes
49,Srikanth (WORKDAY hCM Consultant)\t ...,workday resumes
50,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,workday resumes
51,Vinay kumar .v\nWorkday Functional Consultant\...,workday resumes

In [33]:
dfr.loc[0:1,'category'] = 'Internship'
dfr.loc[2:19,'category'] = 'ReactJS Developer'
dfr.loc[20:29,'category'] = 'Peoplesoft'
dfr.loc[30:40,'category'] = 'SQL Developer'
dfr.loc[41:51,'category'] = 'Workday'
dfr

                                          resume_text           category
0   Name: Ravali P \n\n\n\n                       ...         Internship
1   SUSOVAN  BAG   \n\nSeeking  a  challenging  po...         Internship
2   Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...  ReactJS Developer
3   HARIPRIYA BATTINA \n\nExperience as UI Develop...  ReactJS Developer
4   KAMALAKAR REDDY. A \n\nLinked In: https://www....  ReactJS Developer
5   Naveen Sadhu\n\n\n\n\n\nTitle: software develo...  ReactJS Developer
6   PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...  ReactJS Developer
7   SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...  ReactJS Developer
8   Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...  ReactJS Developer
9   Ui-Developer/ React JS Developer \n\nNAME: KRI...  ReactJS Developer
10  Ui-Developer/ React JS Developer \n\nNAME: KRI...  ReactJS Developer
11  Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...  ReactJS Developer
12  Venkatalakshmi Pedireddy\n\nSoftware Developer...  ReactJS Developer
13  KAMBALA SAI SURENDRA   \n\n \n\n \n\n \n\n\n\n...  ReactJS Developer
14  MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...  ReactJS Developer
15  MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...  ReactJS Developer
16  MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n   ...  ReactJS Developer
17  Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...  ReactJS Developer
18  Ranga Gaganam  \n\n\n\n \n\nProfessional\n\n \...  ReactJS Developer
19  SHAIK ABDUL SHARUK   \n\n2 years’ Experience i...  ReactJS Developer
20  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...         Peoplesoft
21  Classification: Internal\n\nClassification: In...         Peoplesoft
22  SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...         Peoplesoft
23  PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...         Peoplesoft
24  PeopleSoft Administration\n\n \n\nVivekanand S...         Peoplesoft
25  Hari Narayana \t\t              \n\n\t\n\n\n\n...         Peoplesoft
26  Murali\t\t       \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...         Peoplesoft
27  Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...         Peoplesoft
28  Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...         Peoplesoft
29  C O N T A C T :\n\n\n\nAddress: Manyata Tech P...         Peoplesoft
30  ANIL KUMAR MADDUKURI  \t\t\n\nSQL & MSBI Devel...      SQL Developer
31  Aradhana Tripathi\n\n\n\nCurrent Location: Gac...      SQL Developer
32  BUDDHA VAMSI                                  ...      SQL Developer
33  KAMBALLA PRADEEP                              ...      SQL Developer
34  Resume\n\nName     :  Neeraj Mishra\n\n\n\nExp...      SQL Developer
35  SQL DEVELOPER\n\nName: -   Bandi prem sai\n\n\...      SQL Developer
36  SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...      SQL Developer
37  RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...      SQL Developer
38  resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...      SQL Developer
39  Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...      SQL Developer
40  SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...      SQL Developer
41  Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...            Workday
42  Name         : Gopi Krishna Reddy\n\n\t\t\t\t ...            Workday
43  G Himaja\n\n                                  ...            Workday
44  JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...            Workday
45  Mooraboyina Guravaiah\n\nWorkday Integration S...            Workday
46  VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...            Workday
47  Workday HCM  Techno functional Consultant     ...            Workday
48  Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...            Workday
49  Srikanth (WORKDAY hCM Consultant)\t           ...            Workday
50  WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...            Workday
51  Vinay kumar .v\nWorkday Functional Consultant\...            Workday

#### <font color='green'><b>Text Extraction of .pdf files and converting it to pandas dataframe along with the filenames as categories :

In [36]:
res_list2 = []
files2 = glob.glob('C:\\Users\Dell\\Downloads\\Resumes-20230307T054753Z-001\\resume\\**\\*.pdf',recursive=True)
dfp = pd.DataFrame(files2,columns=['category'])
dfp = dfp['category'].str.split('\\').str[7]
dfp.columns = ['category']

for i in files2:
    c = extract_text(i)
    res_list2.append(c)
    
dfd = pd.DataFrame(res_list2,columns=['resume_text'])
dfd = dfd.join(dfp)
dfd

,resume_text,category
0,\n\n \n\nName: M. Prabakaran \nTitle: UI Deve...,Reactjs Developer_Prabakaran_Musquare Technolo...

In [37]:
dfd.loc[0,'category'] = 'ReactJS Developer'
dfd

                                         resume_text           category
0   \n\n \n\nName: M. Prabakaran \nTitle: UI Deve...  ReactJS Developer

#### <font color='orange'><b>Final Dataframe :

In [38]:
df = pd.concat([dfr, dfd, df3], axis=0,ignore_index=1)
df

                                          resume_text           category
0   Name: Ravali P \n\n\n\n                       ...         Internship
1   SUSOVAN  BAG   \n\nSeeking  a  challenging  po...         Internship
2   Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...  ReactJS Developer
3   HARIPRIYA BATTINA \n\nExperience as UI Develop...  ReactJS Developer
4   KAMALAKAR REDDY. A \n\nLinked In: https://www....  ReactJS Developer
..                                                ...                ...
74  Name\t: Naresh Babu Cherukuri\r\rObjective:\rT...            Workday
75  \r\r\r3.3 years of IT experience as Workda...            Workday
76  Shireesh Balasani                             ...            Workday
77  \tWorkday Integration Consultant\r\rName      ...            Workday
78  Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...            Workday

[79 rows x 2 columns]

#### <font color='orange'><b>Saving it in csv form :

In [39]:
df.to_csv("resumes.csv")